import { useCallback,useEffect,useState } from 'react';
import { Download,RefreshCw,Search,FileCheck2,X } from 'lucide-react';
import { consultarFechamento,exportarFechamento,COLUNAS_FECHAMENTO,linhaFechamento } from '../../services/fechamentoLojasService.js';
const defaults={situacao:'aguardando',laudo:'',busca:'',rede:''};
const num=n=>Number(n||0).toLocaleString('pt-BR');
const money=n=>n==null?'Não informado':Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=d=>d?new Date(d).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Sem registro';
export default function FechamentoLojasV2Page(){
 const [filters,setFilters]=useState(defaults),[applied,setApplied]=useState(defaults),[page,setPage]=useState(0),[result,setResult]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(''),[selected,setSelected]=useState(null),[allColumns,setAllColumns]=useState(false);
 const load=useCallback(async signal=>{setLoading(true);setError('');try{const data=await consultarFechamento(applied,page*100,100,true,signal);if(!signal.aborted)setResult(data);}catch(err){if(!signal.aborted)setError(err.message);}finally{if(!signal.aborted)setLoading(false);}},[applied,page]);
 useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)load(controller.signal);});return()=>controller.abort();},[load]);
 const set=(k,v)=>setFilters(f=>({...f,[k]:v}));
 const apply=e=>{e.preventDefault();setPage(0);setApplied({...filters});};
 async function exportExcel(){setExporting(true);setError('');setProgress('Preparando fechamento…');try{const n=await exportarFechamento(applied,(done,total)=>setProgress(`Exportando ${num(done)} de ${num(total)} aparelhos…`));setProgress(`${num(n)} aparelhos exportados.`);}catch(err){setError(err.message);setProgress('');}finally{setExporting(false);}}
 const r=result?.resumo||{};
 return <div className="mx-auto max-w-[1800px] space-y-5 p-4 text-slate-900 md:p-7">
 <header className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-purple-600">Assurant • Gestão</p><h1 className="mt-1 text-3xl font-bold">Fechamento de Lojas</h1><p className="mt-2 text-sm text-slate-500">Todos os aparelhos da fila de cosmética, com ou sem laudo. Sem limite de datas ou grade.</p></div><div className="flex items-center gap-2"><button disabled={loading||exporting} onClick={()=>setApplied(f=>({...f}))} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-semibold disabled:opacity-50"><RefreshCw size={17} className={loading?'animate-spin':''}/>Atualizar</button><button disabled={loading||exporting||!r.total} onClick={exportExcel} className="flex items-center gap-2 rounded-xl bg-purple-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50"><Download size={17}/>Exportar Excel</button></div></header>
 <form onSubmit={apply} className="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4"><label className="text-xs font-semibold text-slate-600">Visão<select className="mt-2 block rounded-lg border p-2.5 text-sm" value={filters.situacao} onChange={e=>set('situacao',e.target.value)}><option value="aguardando">Aguardando cosmética</option><option value="concluida">Cosmética concluída</option><option value="todos">Aguardando + concluídos</option></select></label><label className="text-xs font-semibold text-slate-600">Laudo<select className="mt-2 block rounded-lg border p-2.5 text-sm" value={filters.laudo} onChange={e=>set('laudo',e.target.value)}><option value="">Com e sem laudo</option><option value="sim">Com laudo</option><option value="nao">Sem laudo</option></select></label><label className="text-xs font-semibold text-slate-600">Rede<select className="mt-2 block max-w-56 rounded-lg border p-2.5 text-sm" value={filters.rede} onChange={e=>set('rede',e.target.value)}><option value="">Todas</option>{result?.redes?.map(x=><option key={x}>{x}</option>)}</select></label><label className="min-w-60 flex-1 text-xs font-semibold text-slate-600">Voucher, IMEI, SKU ou loja<div className="mt-2 flex items-center rounded-lg border px-3"><Search size={16}/><input className="w-full p-2.5 text-sm outline-none" placeholder="Buscar aparelho ou loja" value={filters.busca} onChange={e=>set('busca',e.target.value)}/></div></label><button disabled={loading||exporting} className="rounded-lg bg-purple-700 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Aplicar</button></form>
 {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{loading&&<p role="status" className="text-sm text-purple-700">Consultando fechamento…</p>}{progress&&<p role="status" className="text-sm text-purple-700">{progress}</p>}
 {result&&<div className={loading?'pointer-events-none space-y-5 opacity-50':'space-y-5'}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Aparelhos',num(r.total),`${num(r.aguardando)} aguardando • ${num(r.concluidos)} concluídos`],['Com laudo',num(r.com_laudo),'Laudo registrado no Liquida ou no GAIA'],['Sem laudo',num(r.sem_laudo),'Sem registro de laudo nas bases'],['Valor do fechamento',money(r.valor_real),`Preço Real = valor original • ${num(r.sem_valor)} sem valor cadastrado`]].map(([label,value,detail])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></div>)}</div>
 <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><h2 className="text-lg font-bold">Detalhe das transações</h2><p className="mt-1 text-xs text-slate-500">Mais antigos primeiro. O Excel leva todos os registros filtrados, além da página em tela.</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={allColumns} onChange={e=>setAllColumns(e.target.checked)}/>Mostrar as 29 colunas do modelo</label></div>
 <div className="max-h-[650px] overflow-auto"><table className="w-full whitespace-nowrap text-left text-xs"><thead className="sticky top-0 z-10 bg-slate-50 text-slate-500"><tr>{(allColumns?COLUNAS_FECHAMENTO:['Voucher / IMEI','Loja / Rede','Produto / SKU','Situação / Grade','Laudo','Motivo da divergência','Total','Preço Real','Data Trade-in / Cosmética']).map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{result.itens.map(i=><tr key={i.id} className="hover:bg-purple-50/40">{allColumns?linhaFechamento(i).map((v,k)=><td className="px-4 py-3" key={k}>{k===1?<button onClick={()=>setSelected(i)} className="font-bold text-purple-700 hover:underline">{v}</button>:v instanceof Date?v.toLocaleDateString('pt-BR'):[19,20,22].includes(k)?money(v):v||'—'}</td>):<><td className="px-4 py-4"><button className="font-bold text-purple-700 hover:underline" onClick={()=>setSelected(i)}>{i.voucher}</button><p className="mt-1 text-slate-400">{i.imei||'Sem IMEI'}</p></td><td className="px-4 py-4">{i.loja||'Não informado'}<p className="mt-1 text-slate-400">{i.rede||'—'} • {i.codigo_loja||'—'}</p></td><td className="max-w-72 px-4 py-4"><p className="truncate">{i.produto||i.modelo||'—'}</p><p className="mt-1 text-slate-400">{i.sku||'—'}</p></td><td className="px-4 py-4">{i.situacao==='aguardando'?'Aguardando cosmética':'Cosmética concluída'}<p className="mt-1 text-slate-400">Grade: {i.grade||'Não definida'}</p></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 font-semibold ${i.tem_laudo?'bg-amber-50 text-amber-800':'bg-emerald-50 text-emerald-700'}`}>{i.tem_laudo?'Com laudo':'Sem laudo'}</span><p className="mt-2 text-slate-400">{i.tem_laudo?date(i.data_laudo):'Sem registro'}</p></td><td className="max-w-80 whitespace-normal px-4 py-4">{i.tem_laudo?(i.motivo_divergencia||'Motivo não informado'):'N/A'}</td><td className="px-4 py-4">{money(i.total)}</td><td className="px-4 py-4 font-bold">{money(i.preco_real)}</td><td className="px-4 py-4">{date(i.data_tradein)}<p className="mt-1 text-slate-400">Cosmética: {date(i.data_cosmetico)}</p></td></>}</tr>)}{!result.itens.length&&<tr><td colSpan={allColumns?29:9} className="p-10 text-center text-slate-500">Nenhum aparelho encontrado.</td></tr>}</tbody></table></div><div className="flex justify-between border-t p-4 text-sm"><button disabled={loading||page===0} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Anterior</button><span>Página {page+1} de {Math.max(1,Math.ceil(r.total/100))} • {num(r.total)} aparelhos</span><button disabled={loading||(page+1)*100>=r.total} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Próxima</button></div></section>
 <p className="text-xs leading-relaxed text-slate-500">Sem corte de datas. Inclui GAIA e Liquida, independentemente da grade. Laudo determinado pelos registros de laudo e pela data de laudo do histórico. Preço Real mantido no valor original do trade-in. {num(r.sem_tradein)} aparelhos sem cadastro de trade-in; valores ausentes ficam em branco no Excel. Dealer e NF_EMITIDA ficam em branco por não terem fonte de fechamento cadastrada. Consultado em {date(result.consultado_em)}.</p></div>}
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" onClick={()=>setSelected(null)}><div role="dialog" aria-modal="true" aria-label="Detalhes do fechamento" className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);}}><div className="flex justify-between"><div><h2 className="text-xl font-bold">{selected.voucher}</h2><p className="mt-1 text-sm text-slate-500">{selected.tem_laudo?'Com laudo':'Sem laudo'} • {selected.origem_triagem||'Origem não informada'}</p></div><button autoFocus aria-label="Fechar" onClick={()=>setSelected(null)}><X/></button></div><div className="my-4 flex items-center gap-2 rounded-xl bg-purple-50 p-4 text-sm"><FileCheck2 size={20}/>Preço Real: {money(selected.preco_real)} — valor original do trade-in</div><dl className="grid gap-3 sm:grid-cols-2">{linhaFechamento(selected).map((v,k)=><div key={k} className="rounded-lg bg-slate-50 p-3"><dt className="text-xs text-slate-500">{COLUNAS_FECHAMENTO[k]}</dt><dd className="mt-1 break-words text-sm">{v instanceof Date?v.toLocaleDateString('pt-BR'):[19,20,22].includes(k)?money(v):v||'Não informado'}</dd></div>)}</dl></div></div>}
 </div>;
}
