import { createElement, useCallback, useEffect, useState } from 'react';
import { Activity, ArrowRight, Clock3, PackageCheck, RefreshCw, Search, X } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, LineChart, Line } from 'recharts';
import { supabase } from '../../lib/supabase.js';
const STAGES=['Antes do recebimento','Aguardando funcional','Aguardando laudo','Aguardando cosmética','Aguardando armazenagem','Armazenado','Cancelado'];
const fmt=n=>n==null?'—':Number(n).toLocaleString('pt-BR',{maximumFractionDigits:1});
const days=n=>n==null?'—':`${fmt(n)} dias`;
const date=d=>d?new Date(d).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'Sem registro';
const defaults=()=>({inicio:'2026-09-01',fim:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),busca:'',etapa:'',rede:''});
function Card({label,value,detail,icon}) {return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between text-sm text-slate-500"><span>{label}</span>{createElement(icon,{size:19,className:'text-purple-600'})}</div><div className="mt-3 text-3xl font-bold">{value}</div><div className="mt-2 text-xs text-slate-500">{detail}</div></div>;}
export default function GestaoEsteiraV2Page(){
 const [filters,setFilters]=useState(defaults),[applied,setApplied]=useState(defaults),[page,setPage]=useState(0),[result,setResult]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null);
 const load=useCallback(async signal=>{setLoading(true);setError('');try{const {data,error:err}=await supabase.rpc('assurant_gestao_esteira',{p_inicio:applied.inicio,p_fim:applied.fim,p_busca:applied.busca.trim(),p_etapa:applied.etapa,p_rede:applied.rede,p_pagina:page}).abortSignal(signal);if(err)throw err;if(!signal.aborted)setResult(data);}catch(err){if(!signal.aborted)setError(err.message||'Não foi possível consultar a esteira.');}finally{if(!signal.aborted)setLoading(false);}},[applied,page]);
 useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)load(controller.signal);});return()=>controller.abort();},[load]);
 const r=result?.resumo||{},stages=STAGES.map(etapa=>({etapa,quantidade:result?.etapas?.find(e=>e.etapa===etapa)?.quantidade||0}));
 const set=(key,value)=>setFilters(v=>({...v,[key]:value}));
 const apply=e=>{e.preventDefault();if(filters.fim<filters.inicio){setError('Período inválido.');return;}setPage(0);setApplied({...filters});};
 const stage=etapa=>{setPage(0);setFilters(v=>({...v,etapa}));setApplied(v=>({...v,etapa}));};
 return <div className="mx-auto max-w-[1700px] space-y-6 p-4 text-slate-900 md:p-7">
 <header className="flex flex-wrap items-center justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-widest text-purple-600">Gestão • Trade-in</div><h1 className="mt-1 text-3xl font-bold">Gestão da Esteira</h1><p className="mt-2 text-sm text-slate-500">Do início na loja à primeira armazenagem no estoque.</p></div><button onClick={()=>setApplied(v=>({...v}))} disabled={loading} className="flex items-center gap-2 rounded-xl border bg-white px-4 py-3 text-sm font-semibold disabled:opacity-50"><RefreshCw size={16} className={loading?'animate-spin':''}/>Atualizar</button></header>
 <form onSubmit={apply} className="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4">{[['inicio','Início do trade-in — de'],['fim','Até']].map(([k,label])=><label key={k} className="text-xs font-semibold text-slate-600">{label}<input required type="date" value={filters[k]} onChange={e=>set(k,e.target.value)} className="mt-2 block rounded-lg border border-slate-200 p-2.5 text-sm"/></label>)}<label className="min-w-52 flex-1 text-xs font-semibold text-slate-600">Voucher, IMEI, modelo ou loja<div className="mt-2 flex items-center rounded-lg border border-slate-200 px-3"><Search size={16}/><input value={filters.busca} onChange={e=>set('busca',e.target.value)} placeholder="Buscar aparelho" className="w-full p-2.5 text-sm outline-none"/></div></label><label className="text-xs font-semibold text-slate-600">Etapa<select value={filters.etapa} onChange={e=>set('etapa',e.target.value)} className="mt-2 block rounded-lg border border-slate-200 p-2.5 text-sm"><option value="">Todas</option>{STAGES.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Rede<select value={filters.rede} onChange={e=>set('rede',e.target.value)} className="mt-2 block max-w-52 rounded-lg border border-slate-200 p-2.5 text-sm"><option value="">Todas</option>{result?.redes?.map(s=><option key={s}>{s}</option>)}</select></label><button disabled={loading} className="rounded-lg bg-purple-700 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Aplicar</button></form>
 {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{loading&&<div role="status" className="text-sm text-purple-700">Consultando esteira…</div>}
 {!error&&result&&<div className={loading?'pointer-events-none space-y-6 opacity-50':'space-y-6'}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Trade-ins no período" value={fmt(r.total)} detail={`${fmt(r.cancelados)} cancelados`} icon={Activity}/><Card label="Armazenagem concluída" value={fmt(r.armazenados)} detail="Primeira alocação registrada" icon={PackageCheck}/><Card label="Pendentes de armazenagem" value={fmt(r.pendentes)} detail={`Tempo em aberto médio: ${days(r.aging_medio)}`} icon={Clock3}/><Card label="Prazo médio ponta a ponta" value={days(r.prazo_medio)} detail={`Mediana ${days(r.mediana)} • P90 ${days(r.p90)} • ${fmt(r.amostra_prazo)} aparelhos`} icon={ArrowRight}/></div>
 <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><h2 className="text-lg font-bold">Fila por etapa</h2><button onClick={()=>stage('')} className="text-sm font-semibold text-purple-700">Ver todas</button></div><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-7">{stages.map(s=><button key={s.etapa} onClick={()=>stage(s.etapa)} className={`rounded-xl border p-3 text-left ${applied.etapa===s.etapa?'border-purple-500 bg-purple-50':'border-slate-200 hover:bg-slate-50'}`}><div className="text-2xl font-bold">{fmt(s.quantidade)}</div><div className="mt-2 text-xs text-slate-500">{s.etapa}</div></button>)}</div></section>
 <section><h2 className="mb-3 text-lg font-bold">Tempo médio entre etapas</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Trade-in → Recebimento','recebimento'],['Recebimento → Funcional','funcional'],['Funcional → Cosmética','cosmetica'],['Cosmética → Armazenagem','armazenagem']].map(([label,k])=><div key={k} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-purple-800">{days(r[`${k}_medio`])}</p><p className="mt-1 text-xs text-slate-400">{fmt(r[`${k}_n`])} aparelhos com datas válidas</p></div>)}</div></section>
 <div className="grid gap-4 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-bold">Entradas por semana de início</h2><ResponsiveContainer width="100%" height={230}><BarChart data={result.semanas}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="semana" tickFormatter={s=>s.slice(8,10)+'/'+s.slice(5,7)}/><YAxis/><Tooltip/><Bar dataKey="entradas" name="Trade-ins iniciados" fill="#7c3aed" radius={[5,5,0,0]}/><Bar dataKey="armazenados" name="Já armazenados desta semana" fill="#10b981" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></section><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="mb-4 font-bold">Prazo médio por semana de início</h2><ResponsiveContainer width="100%" height={230}><LineChart data={result.semanas}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="semana" tickFormatter={s=>s.slice(8,10)+'/'+s.slice(5,7)}/><YAxis unit=" d"/><Tooltip formatter={v=>days(v)}/><Line dataKey="prazo_medio" name="Trade-in até armazenagem" stroke="#7c3aed" strokeWidth={3}/></LineChart></ResponsiveContainer></section></div>
 <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex justify-between p-5"><div><h2 className="text-lg font-bold">Acompanhamento dos aparelhos</h2><p className="text-xs text-slate-500">Pendentes mais antigos primeiro. Clique no voucher para abrir a linha do tempo.</p></div><span className="text-sm text-slate-500">{fmt(r.total)} registros</span></div><div className="overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Voucher / IMEI','Modelo / Rede','Etapa','Início trade-in','Recebimento','Funcional','Cosmética','Armazenagem','Prazo total / em aberto'].map(h=><th className="px-4 py-3 font-semibold" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{result.itens.map(i=><tr key={i.voucher} className="hover:bg-purple-50/40"><td className="px-4 py-4"><button className="font-bold text-purple-700 hover:underline" onClick={()=>setSelected(i)}>{i.voucher}</button><div className="mt-1 text-slate-400">{i.imei||'Sem IMEI'}</div></td><td className="max-w-60 px-4 py-4"><div className="truncate">{i.modelo||'—'}</div><div className="mt-1 text-slate-400">{i.rede||'—'}</div></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 ${i.etapa==='Armazenado'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{i.etapa}</span>{i.datas_inconsistentes&&<div className="mt-2 text-red-600">Conferir datas</div>}</td>{['inicio','recebimento','funcional','cosmetica','armazenagem'].map(k=><td key={k} className="px-4 py-4">{date(i[k])}</td>)}<td className="px-4 py-4 font-bold">{days(i.armazenagem?i.prazo_total_dias:i.aging_dias)}<div className="mt-1 font-normal text-slate-400">{i.cancelado?'Cancelado':i.armazenagem?'Concluído':'Em aberto'}</div></td></tr>)}{!result.itens.length&&<tr><td colSpan={9} className="p-8 text-center">Nenhum aparelho encontrado para estes filtros.</td></tr>}</tbody></table></div><div className="flex justify-between border-t border-slate-200 p-4 text-sm"><button disabled={page===0||loading} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Anterior</button><span>Página {page+1} de {Math.max(1,Math.ceil(r.total/100))}</span><button disabled={(page+1)*100>=r.total||loading} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-4 py-2 disabled:opacity-40">Próxima</button></div></section>
 <p className="text-xs leading-relaxed text-slate-500">Período filtrado pela data de início do trade-in. Prazos em dias corridos; cancelados excluídos das médias. Tempos negativos e datas ausentes não entram na média do respectivo trecho. {fmt(r.inconsistentes)} registros com sequência de datas inconsistente. Funcional → Cosmética inclui eventual passagem por laudo. Histórico GAIA e triagens Liquida considerados. Consultado em {date(result.atualizado_em)}.</p></div>}
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" onClick={()=>setSelected(null)}><div role="dialog" aria-modal="true" aria-label={`Linha do tempo ${selected.voucher}`} className="max-h-[90vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-6 shadow-2xl" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);}}><div className="flex justify-between"><div><h2 className="text-xl font-bold">{selected.voucher}</h2><p className="mt-1 text-sm text-slate-500">{selected.imei} • {selected.modelo}</p></div><button autoFocus aria-label="Fechar linha do tempo" onClick={()=>setSelected(null)}><X/></button></div><p className="my-4 text-sm">{selected.loja} • {selected.rede}</p><div className="space-y-4 border-l-2 border-purple-200 pl-5">{[['Início do trade-in','inicio'],['Aprovação','aprovacao'],['Recebimento','recebimento'],['Triagem funcional','funcional'],['Laudo (quando necessário)','laudo'],['Triagem cosmética','cosmetica'],['Primeira armazenagem','armazenagem'],['Entrada Oracle','oracle']].map(([label,k])=><div key={k}><p className="text-sm font-semibold">{label}</p><p className="text-xs text-slate-500">{date(selected[k])}</p></div>)}</div><div className="mt-5 rounded-xl bg-purple-50 p-4 text-sm"><p className="font-bold">{selected.etapa} • {days(selected.armazenagem?selected.prazo_total_dias:selected.aging_dias)}</p><p className="mt-1">{selected.fonte_armazenagem||'Armazenagem ainda sem registro'} • Triagem: {selected.origem_triagem||'Sem registro'}</p><p className="mt-2 text-xs">Status trade-in: {selected.status_tradein||'—'}<br/>Status Liquida: {selected.status_liquida||'—'}</p></div></div></div>}
 </div>;
}
