import { useEffect, useMemo, useState } from 'react';
import { Download, RefreshCw, Trophy, TrendingUp, SlidersHorizontal } from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts';
import { consultarProducao, ETAPAS_PRODUCAO, resumirProducao, distribuirBonus } from '../../services/producaoEsteiraService.js';

const fmt = n => Number(n || 0).toLocaleString('pt-BR', { maximumFractionDigits: 1 });
const money = n => Number(n || 0).toLocaleString('pt-BR', { style:'currency', currency:'BRL' });
const today = () => new Intl.DateTimeFormat('en-CA', { timeZone:'America/Sao_Paulo', year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date());
const initial = () => { const fim=today(); return { modo:'mes', dia:fim, mes:fim.slice(0,7), ano:fim.slice(0,4), inicio:fim.slice(0,7)+'-01', fim, agrupamento:'dia' }; };
function intervalo(f) {
  if (f.modo==='dia') return { ...f, inicio:f.dia, fim:f.dia, agrupamento:'dia' };
  if (f.modo==='mes') { const [y,m]=f.mes.split('-').map(Number); return { ...f, inicio:f.mes+'-01', fim:f.mes+'-'+new Date(Date.UTC(y,m,0)).getUTCDate(), agrupamento:f.agrupamento }; }
  if (f.modo==='ano') return { ...f, inicio:f.ano+'-01-01', fim:f.ano+'-12-31', agrupamento:f.agrupamento };
  return { ...f };
}
const label = d => d ? `${d.slice(8,10)}/${d.slice(5,7)}/${d.slice(0,4)}` : '';
const button = 'inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-40';
const input = 'mt-1 block w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal';
const box = 'rounded-2xl border border-slate-200 bg-white p-5 shadow-sm';

export default function ProducaoEsteiraV2Page() {
  const [filters,setFilters]=useState(initial), [applied,setApplied]=useState(()=>intervalo(initial()));
  const [result,setResult]=useState(null), [loading,setLoading]=useState(true), [error,setError]=useState('');
  const [etapa,setEtapa]=useState(''), [canal,setCanal]=useState(''), [colaborador,setColaborador]=useState('');
  const [pesos,setPesos]=useState({}), [valor,setValor]=useState(''), [showBonus,setShowBonus]=useState(false), [exporting,setExporting]=useState(false);
  const set=(k,v)=>setFilters(f=>({...f,[k]:v}));
  useEffect(()=>{
    const c=new AbortController();
    async function load() { setLoading(true);setError('');setResult(null); try { const data=await consultarProducao(applied,c.signal);if(!c.signal.aborted)setResult(data); } catch(e) { if(!c.signal.aborted)setError(e.message||'Não foi possível consultar a produção.'); } finally {if(!c.signal.aborted)setLoading(false);} }
    load();return()=>c.abort();
  },[applied]);
  const dados=result?.dados||[];
  const pessoas=useMemo(()=>[...new Map(dados.filter(d=>d.colaborador_id).map(d=>[d.colaborador_id,{id:d.colaborador_id,nome:d.colaborador}])).values()].sort((a,b)=>a.nome.localeCompare(b.nome)),[dados]);
  const filtered=useMemo(()=>dados.filter(d=>(!etapa||d.etapa===etapa)&&(!canal||d.canal===canal)&&(!colaborador||d.colaborador_id===colaborador)),[dados,etapa,canal,colaborador]);
  const resumo=useMemo(()=>resumirProducao(filtered,showBonus?pesos:{}),[filtered,pesos,showBonus]);
  const bonus=useMemo(()=>distribuirBonus(resumo.ranking,valor),[resumo.ranking,valor]);
  const visibleStages=ETAPAS_PRODUCAO.filter(s=>(!etapa||s.id===etapa)&&(!canal||filtered.some(d=>d.etapa===s.id)));
  const serie=useMemo(()=>{
    if (!result) return [];
    const existentes=new Map(resumo.periodos.map(p=>[p.periodo,p]));
    const d=new Date(applied.inicio+'T12:00:00Z'), fim=new Date((applied.fim<today()?applied.fim:today())+'T12:00:00Z');
    if(applied.agrupamento==='mes') d.setUTCDate(1);
    if(applied.agrupamento==='ano') {d.setUTCMonth(0);d.setUTCDate(1);}
    const rows=[];
    while(d<=fim) { const periodo=d.toISOString().slice(0,10); const row=existentes.get(periodo)||{periodo,total:0}; rows.push({...Object.fromEntries(ETAPAS_PRODUCAO.map(s=>[s.id,0])),...row}); if(applied.agrupamento==='ano')d.setUTCFullYear(d.getUTCFullYear()+1);else if(applied.agrupamento==='mes')d.setUTCMonth(d.getUTCMonth()+1);else d.setUTCDate(d.getUTCDate()+1); }
    return rows;
  },[result,resumo.periodos,applied]);
  const top=resumo.ranking.slice(0,5);
  const porColaborador=new Map();
  for(const d of filtered){const key=d.periodo+'|'+d.colaborador_id;porColaborador.set(key,(porColaborador.get(key)||0)+Number(d.producao||0));}
  const serieColaboradores=serie.map(row=>({periodo:row.periodo,...Object.fromEntries(top.map(p=>[p.id,porColaborador.get(row.periodo+'|'+p.id)||0]))}));
  const axisLabel=d=>applied.agrupamento==='ano'?d.slice(0,4):applied.agrupamento==='mes'?`${d.slice(5,7)}/${d.slice(0,4)}`:label(d).slice(0,5);
  function apply(e) { e.preventDefault();const f=intervalo(filters);if(!f.inicio||!f.fim||f.fim<f.inicio){setError('Informe um período válido.');return;} setApplied(f); }
  async function exportExcel() {
    setExporting(true);
    try { const XLSX=await import('xlsx'), wb=XLSX.utils.book_new();
      const rows=resumo.ranking.map(p=>({'Posição':p.posicao,'Colaborador':p.nome,'ID colaborador':p.id,'Produção':p.producao,'Retrabalho':p.retrabalho,'Dias ativos':p.diasAtivos,'Média/dia ativo':Number(p.media.toFixed(2)),'Pontos simulados':p.pontos,'Participação (%)':resumo.ranking.reduce((s,x)=>s+x.pontos,0)?Number((p.pontos/resumo.ranking.reduce((s,x)=>s+x.pontos,0)*100).toFixed(2)):0,'Bônus simulado (R$)':bonus.get(p.id)||0,...Object.fromEntries(visibleStages.map(s=>[s.nome,p.etapas[s.id]||0]))}));
      const sheets=[['Ranking',rows],['Produção por período',serie.map(p=>({'Período':p.periodo,...Object.fromEntries(visibleStages.map(s=>[s.nome,p[s.id]||0]))}))],['Base agregada',filtered.map(d=>({...d,dias_ativos:(d.dias_ativos||[]).join(', ')}))],['Critérios',[{'Início':applied.inicio,'Fim':applied.fim,'Agrupamento':applied.agrupamento,'Etapa':etapa||'Todas','Canal':canal||'Todos','Colaborador':colaborador||'Todos','Valor bônus simulado':Number(valor)||0,'Consultado em':result.atualizado_em,'Regra':'Produção concluída por etapa; retrabalho e registros sem responsável fora dos pontos; expedição em volumes; média por dias com produção, sem controle de jornada.'},...ETAPAS_PRODUCAO.map(s=>({'Etapa':s.nome,'Peso simulado':pesos[s.id]??1}))]]];
      for(const [name,rows] of sheets){const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=Object.keys(rows[0]||{}).map(k=>({wch:Math.min(45,Math.max(18,k.length+3))}));XLSX.utils.book_append_sheet(wb,ws,name);}
      XLSX.writeFile(wb,`Producao_Esteira_${applied.inicio}_${applied.fim}.xlsx`);
    } catch(e) { setError(e.message||'Erro ao exportar Excel.'); } finally { setExporting(false); }
  }
  return <div className="mx-auto max-w-[1800px] space-y-6 p-4 text-slate-900 md:p-7">
    <header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-purple-600">Gestão • Produção</p><h1 className="mt-1 text-3xl font-bold">Produção da Esteira</h1><p className="mt-2 text-sm text-slate-500">Produção realizada por etapa e colaborador, do recebimento à expedição.</p></div><div className="flex gap-2"><button className={button} disabled={loading} onClick={()=>setApplied(p=>({...p}))}><RefreshCw size={16} className={loading?'animate-spin':''}/>Atualizar</button><button className={button} disabled={loading||!result||exporting} onClick={exportExcel}><Download size={16}/>{exporting?'Exportando…':'Excel'}</button></div></header>
    <form onSubmit={apply} className={`${box} flex flex-wrap items-end gap-3`}><label className="text-xs font-semibold text-slate-600">Visão<select aria-label="Visão" value={filters.modo} onChange={e=>setFilters(f=>({...f,modo:e.target.value,agrupamento:e.target.value==='ano'?'mes':'dia'}))} className={input}>{[['dia','Dia'],['periodo','Período específico'],['mes','Mês'],['ano','Ano']].map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label>
      {filters.modo==='dia'&&<label className="text-xs font-semibold text-slate-600">Data<input required type="date" value={filters.dia} onChange={e=>set('dia',e.target.value)} className={input}/></label>}
      {filters.modo==='mes'&&<label className="text-xs font-semibold text-slate-600">Mês<input required type="month" value={filters.mes} onChange={e=>set('mes',e.target.value)} className={input}/></label>}
      {filters.modo==='ano'&&<label className="text-xs font-semibold text-slate-600">Ano<input required type="number" min="2024" max="2100" value={filters.ano} onChange={e=>set('ano',e.target.value)} className={input}/></label>}
      {filters.modo==='periodo'&&[['inicio','De'],['fim','Até']].map(([k,n])=><label key={k} className="text-xs font-semibold text-slate-600">{n}<input required type="date" value={filters[k]} onChange={e=>set(k,e.target.value)} className={input}/></label>)}
      {filters.modo!=='dia'&&<label className="text-xs font-semibold text-slate-600">Agrupar gráficos<select aria-label="Agrupar gráficos" value={filters.agrupamento} onChange={e=>set('agrupamento',e.target.value)} className={input}>{[['dia','Por dia'],['mes','Por mês'],['ano','Por ano']].map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label>}
      <button className="rounded-xl bg-purple-700 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40" disabled={loading}>Consultar</button>
    </form>
    {loading&&<p role="status" className="text-sm text-purple-700">Apurando produção da esteira…</p>}{error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {result&&<><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-semibold">Etapa<select aria-label="Etapa" className={input} value={etapa} onChange={e=>setEtapa(e.target.value)}><option value="">Todas as etapas</option>{ETAPAS_PRODUCAO.map(s=><option key={s.id} value={s.id}>{s.nome}</option>)}</select></label><label className="text-xs font-semibold">Canal<select aria-label="Canal" className={input} value={canal} onChange={e=>setCanal(e.target.value)}><option value="">Todos</option>{['Trade-in','Estoque','B2C','B2B'].map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs font-semibold">Colaborador<select aria-label="Colaborador" className={input} value={colaborador} onChange={e=>setColaborador(e.target.value)}><option value="">Todos</option>{pessoas.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><p className="pb-2 text-xs text-slate-500">Período consultado: {label(applied.inicio)} a {label(applied.fim)} • Horário de Brasília</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Produção concluída',fmt(resumo.total),'Soma de execuções nas etapas, incluindo volumes de expedição'],['Com responsável',fmt(resumo.total-resumo.semResponsavel),`${fmt(resumo.ranking.length)} colaboradores no período`],['Sem responsável',fmt(resumo.semResponsavel),'Visíveis na produção; fora da simulação de bônus'],['Retrabalho registrado',fmt(resumo.retrabalho),'Separado da produção e dos pontos para bônus']].map(([n,v,d])=><div key={n} className={box}><p className="text-sm text-slate-500">{n}</p><p className="my-2 text-3xl font-bold">{v}</p><p className="text-xs text-slate-500">{d}</p></div>)}</div>
    <section className={box}><h2 className="mb-4 text-lg font-bold">Produção por etapa</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">{visibleStages.map(s=><button key={s.id} onClick={()=>setEtapa(etapa===s.id?'':s.id)} className="rounded-xl border border-slate-100 p-3 text-left hover:bg-purple-50"><span className="mb-2 block h-1 w-8 rounded" style={{background:s.cor}}/><p className="text-2xl font-bold">{fmt(resumo.etapas.get(s.id)?.producao)}</p><p className="mt-1 text-xs font-semibold">{s.nome}</p><p className="mt-1 text-xs text-slate-400">{resumo.etapas.get(s.id)?.unidade||(s.id==='expedicao'?'volumes':'itens')} • {fmt(resumo.etapas.get(s.id)?.retrabalho)} retrabalhos</p></button>)}</div></section>
    {!filtered.length&&<div className={box}>Nenhuma produção encontrada para os filtros selecionados.</div>}
    <section className={box}><h2 className="mb-1 flex items-center gap-2 text-lg font-bold"><TrendingUp size={20}/>Evolução da produção</h2><p className="mb-5 text-xs text-slate-500">Execuções concluídas na data de cada atividade. Dias sem produção aparecem com zero.</p><ResponsiveContainer width="100%" height={330}><LineChart data={serie}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="periodo" tickFormatter={axisLabel} minTickGap={28}/><YAxis allowDecimals={false}/><Tooltip labelFormatter={axisLabel}/><Legend/>{visibleStages.map(s=><Line isAnimationActive={false} key={s.id} dataKey={s.id} name={s.nome} stroke={s.cor} strokeWidth={2} dot={serie.length<3} activeDot={{r:5}}/>)}</LineChart></ResponsiveContainer></section>
    <section className={box}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold"><Trophy size={20} className="text-amber-500"/>Ranking por colaborador</h2><p className="mt-1 text-xs text-slate-500">Escolha uma etapa para comparar a mesma atividade. Empates recebem a mesma posição.</p></div><button className={button} onClick={()=>setShowBonus(v=>!v)} aria-expanded={showBonus}><SlidersHorizontal size={16}/>Simular bônus</button></div>
    {showBonus&&<div className="my-5 rounded-xl border border-purple-100 bg-purple-50 p-4"><div className="flex flex-wrap items-end gap-4"><label className="text-xs font-semibold">Valor total a distribuir (R$)<input type="number" min="0" step="0.01" value={valor} onChange={e=>setValor(e.target.value)} className={input} placeholder="0,00"/></label><p className="max-w-2xl text-xs leading-relaxed text-purple-900">Simulação proporcional aos pontos: produção × peso da etapa. Pesos iniciais iguais a 1; ajuste conforme o esforço das atividades. Retrabalho e produção sem responsável não geram pontos. O valor considera os filtros atuais; simulação sem aprovação ou pagamento automático.</p></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">{visibleStages.map(s=><label key={s.id} className="text-xs text-purple-900">{s.nome}<input type="number" min="0" max="1000" step="0.1" value={pesos[s.id]??1} onChange={e=>setPesos(p=>({...p,[s.id]:Math.min(1000,Math.max(0,Number(e.target.value)||0))}))} className={input}/></label>)}</div></div>}
    <div className="mt-5 overflow-x-auto"><table className="w-full whitespace-nowrap text-left text-xs"><thead className="bg-slate-50"><tr>{['Posição','Colaborador','Produção','Retrabalho','Dias ativos','Média / dia ativo',...(showBonus?['Pontos','Participação','Bônus simulado']:[]),...visibleStages.map(s=>s.nome)].map(h=><th key={h} className="px-3 py-3 font-semibold text-slate-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{resumo.ranking.map(p=><tr key={p.id} className="hover:bg-purple-50/40"><td className="px-3 py-4 font-bold text-purple-700">{p.posicao}º</td><td className="px-3 py-4 font-semibold">{p.nome}</td><td className="px-3 py-4 font-bold">{fmt(p.producao)}</td><td className="px-3 py-4">{fmt(p.retrabalho)}</td><td className="px-3 py-4">{fmt(p.diasAtivos)}</td><td className="px-3 py-4">{fmt(p.media)}</td>{showBonus&&<><td className="px-3 py-4">{fmt(p.pontos)}</td><td className="px-3 py-4">{fmt(resumo.ranking.reduce((s,p)=>s+p.pontos,0)?p.pontos/resumo.ranking.reduce((s,p)=>s+p.pontos,0)*100:0)}%</td><td className="px-3 py-4 font-bold text-emerald-700">{money(bonus.get(p.id))}</td></>}{visibleStages.map(s=><td key={s.id} className="px-3 py-4">{fmt(p.etapas[s.id])}</td>)}</tr>)}</tbody></table>{!resumo.ranking.length&&<p className="py-8 text-center text-sm text-slate-500">Nenhuma execução atribuída a colaborador para estes filtros.</p>}</div><p className="mt-4 text-xs leading-relaxed text-slate-500">Dias ativos = dias com produção concluída registrada. Média por dia ativo não considera horas, jornada, presença ou qualidade. O total conta execuções por etapa: um aparelho pode participar de várias etapas. O ranking geral mistura atividades; a comparação por etapa e os pesos apoiam sua análise.</p></section>
    {top.length>0&&<section className={box}><h2 className="mb-4 text-lg font-bold">Evolução dos 5 primeiros colaboradores</h2><ResponsiveContainer width="100%" height={280}><LineChart data={serieColaboradores}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="periodo" tickFormatter={axisLabel} minTickGap={28}/><YAxis allowDecimals={false}/><Tooltip labelFormatter={axisLabel}/><Legend/>{top.map((p,i)=><Line isAnimationActive={false} key={p.id} dataKey={p.id} name={p.nome} stroke={ETAPAS_PRODUCAO[i].cor} strokeWidth={2} dot={serie.length<3}/>)}</LineChart></ResponsiveContainer></section>}
    <section className={box}><h2 className="mb-4 text-lg font-bold">Produção por {applied.agrupamento==='dia'?'dia':applied.agrupamento==='mes'?'mês':'ano'}</h2><div className="max-h-96 overflow-auto"><table className="w-full whitespace-nowrap text-left text-xs"><thead className="sticky top-0 bg-slate-50"><tr><th className="px-3 py-3">Período</th>{visibleStages.map(s=><th key={s.id} className="px-3 py-3">{s.nome}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{serie.map(p=><tr key={p.periodo}><td className="px-3 py-3 font-semibold">{axisLabel(p.periodo)}</td>{visibleStages.map(s=><td key={s.id} className="px-3 py-3">{fmt(p[s.id])}</td>)}</tr>)}</tbody></table></div></section>
    <p className="text-xs leading-relaxed text-slate-500">Histórico GAIA e Liquida conforme registros disponíveis. Responsável de importação não é tratado como executor. Entrada Oracle usa confirmação ou data operacional; faturamento B2B usa data de faturamento e quantidade da NF, com responsável não identificado. Expedição conta volumes bipados no romaneio, sem inferir coleta física. Retrabalho histórico considera revisões funcionais auditadas; outras repetições anteriores ao início deste acompanhamento podem não estar disponíveis. Consultado em {new Date(result.atualizado_em).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}.</p>
    </>}
  </div>;
}
